# Creating Customers Dataset

The objective is to join all tables of Olist dataset into one to carry out an exploration of the orders data relying on one single datasource.

In [176]:
import pandas as pd
import numpy as np
import datetime

In [177]:
customer_data=pd.read_csv('olist_customers_dataset.csv')
#orders_dataset contains dates, parse_dates arg should be called to convert them to datetime objects
order_data=pd.read_csv('olist_orders_dataset.csv',parse_dates=['order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date'])
order_items=pd.read_csv('olist_order_items_dataset.csv')
payments=pd.read_csv('olist_order_payments_dataset.csv')
reviews=pd.read_csv('olist_order_reviews_dataset.csv')
products=pd.read_csv('olist_products_dataset.csv')
seller_geo=pd.read_csv('olist_sellers_dataset.csv')
product_category=pd.read_csv('product_category_name_translation.csv')

In [178]:
# order_data: check if dates are datetime 
order_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
order_id                         99441 non-null object
customer_id                      99441 non-null object
order_status                     99441 non-null object
order_purchase_timestamp         99441 non-null datetime64[ns]
order_approved_at                99281 non-null datetime64[ns]
order_delivered_carrier_date     97658 non-null datetime64[ns]
order_delivered_customer_date    96476 non-null datetime64[ns]
order_estimated_delivery_date    99441 non-null datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [179]:
#order_data: check format of dates
order_data.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

<img src="data_schema.png">

In [180]:
# 1. merge customers and orders to merge customer data and order id, to later merge other tables
df=customer_data.merge(order_data, on='customer_id')
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15

In [181]:
# 2. merge df with order items data for additional data related to each order
df=df.merge(order_items, on='order_id')
df=df[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date','product_id', 'seller_id', 'price',
       'freight_value']]

In [182]:
# 3. merge df wtih payments
df=df.merge(payments,on='order_id')
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,product_id,seller_id,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,124.99,21.88,1,credit_card,2,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,289.00,46.48,1,credit_card,8,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,139.94,17.79,1,credit_card,7,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,149.94,23.36,1,credit_card,1,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,230.00,22.25,1,credit_card,8,252.25

In [183]:
# 4. merge df with reviews, left merge as not all reviews data have customer_id
df=df.merge(reviews, on='order_id')
df=df[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'product_id',
       'seller_id', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'review_score']]
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,order_estimated_delivery_date,product_id,seller_id,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_score
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,2017-06-05,a9516a079e37a9c9c36b9b78b10169e8,7c67e1448b00f6e969d365cea6b010ab,124.99,21.88,1,credit_card,2,146.87,4
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,2018-02-06,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,289.00,46.48,1,credit_card,8,335.48,5
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,2018-06-13,bd07b66896d6f1494f5b86251848ced7,7c67e1448b00f6e969d365cea6b010ab,139.94,17.79,1,credit_card,7,157.73,5
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,2018-04-10,a5647c44af977b148e0a3a4751a09e2e,7c67e1448b00f6e969d365cea6b010ab,149.94,23.36,1,credit_card,1,173.30,5
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,2018-08-15,9391a573abe00141c56e38d84d7d5b3b,4a3ca9315b744ce9f8e9374361493884,230.00,22.25,1,credit_card,8,252.25,5

In [184]:
# 5. merge with products
df=df.merge(products, on='product_id')
df=df[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'seller_id', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_score',
       'product_category_name']]
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,order_estimated_delivery_date,seller_id,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_category_name
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,2017-06-05,7c67e1448b00f6e969d365cea6b010ab,124.99,21.88,1,credit_card,2,146.87,4,moveis_escritorio
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,2017-12-19,7c67e1448b00f6e969d365cea6b010ab,112.99,24.90,1,credit_card,1,275.79,1,moveis_escritorio
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,2017-12-19,7c67e1448b00f6e969d365cea6b010ab,112.99,24.90,1,credit_card,1,275.79,1,moveis_escritorio
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,2017-06-12,7c67e1448b00f6e969d365cea6b010ab,124.99,15.62,1,credit_card,7,140.61,3,moveis_escritorio
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,2018-03-22,7c67e1448b00f6e969d365cea6b010ab,106.99,30.59,1,credit_card,10,137.58,4,moveis_escritorio

In [185]:
# 6. merge with product_category to have prod cat english
df=df.merge(product_category, on='product_category_name')
#keep only englsh prod cat
df=df[['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'seller_id', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value', 'review_score','product_category_name_english']]
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,order_estimated_delivery_date,seller_id,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_category_name_english
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,2017-06-05,7c67e1448b00f6e969d365cea6b010ab,124.99,21.88,1,credit_card,2,146.87,4,office_furniture
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,2017-12-19,7c67e1448b00f6e969d365cea6b010ab,112.99,24.90,1,credit_card,1,275.79,1,office_furniture
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,2017-12-19,7c67e1448b00f6e969d365cea6b010ab,112.99,24.90,1,credit_card,1,275.79,1,office_furniture
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,2017-06-12,7c67e1448b00f6e969d365cea6b010ab,124.99,15.62,1,credit_card,7,140.61,3,office_furniture
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,2018-03-22,7c67e1448b00f6e969d365cea6b010ab,106.99,30.59,1,credit_card,10,137.58,4,office_furniture

In [186]:
# 7. merge df with seller geo data
df=df.merge(seller_geo, on='seller_id')
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_category_name_english,seller_zip_code_prefix,seller_city,seller_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,21.88,1,credit_card,2,146.87,4,office_furniture,8577,itaquaquecetuba,SP
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,24.90,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,24.90,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,15.62,1,credit_card,7,140.61,3,office_furniture,8577,itaquaquecetuba,SP
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,30.59,1,credit_card,10,137.58,4,office_furniture,8577,itaquaquecetuba,SP

## Data Assessing

In [187]:
#Visual assessment
df

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_category_name_english,seller_zip_code_prefix,seller_city,seller_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,21.88,1,credit_card,2,146.87,4,office_furniture,8577,itaquaquecetuba,SP
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,24.90,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,24.90,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,15.62,1,credit_card,7,140.61,3,office_furniture,8577,itaquaquecetuba,SP
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,30.59,1,credit_card,10,137.58,4,office_furniture,8577,itaquaquecetuba,SP
5,fd3a0b1bd209f0e7d420c9c3d1127613,567ab47ca4deb92d46dbf54dce07d0a7,88460,angelina,SC,574fe1739f65af76badd0999db300b4f,delivered,2017-03-23 15:10:17,2017-03-23 15:25:11,2017-03-28 18:23:51,...,15.06,1,credit_card,5,142.05,4,office_furniture,8577,itaquaquecetuba,SP
6,fbd40c083aa8cddebb5265b2ba6aaf2e,f40ab89b622248b7ca125af4b486b887,32341,contagem,MG,e0b26f14d2bcc710bb02f77a4628763b,delivered,2017-05-16 10:00:49,2017-05-17 03:45:27,2017-05-23 10:35:48,...,30.71,1,boleto,1,155.70,4,office_furniture,8577,itaquaquecetuba,SP
7,10558ef4afea173bfb5e2cbe3d5b0bb5,749943913a9851a39c9baf51877fbab6,78134,varzea grande,MT,eaae5bd20fb15d85aa673d9b7c0e8ca5,delivered,2017-03-18 23:04:36,2017-03-18 23:04:36,2017-03-28 06:29:47,...,21.34,1,credit_card,2,148.33,2,office_furniture,8577,itaquaquecetuba,SP
8,1c37c0f0cd1d88d46d9fc9494762abbd,432ecfa8b7b7ad2663c7abed0dc83c51,31270,belo horizonte,MG,c4e2bd2043fbd75b325a47adfabf0d77,delivered,2018-03-15 07:45:10,2018-03-15 07:55:24,2018-03-27 15:58:41,...,33.08,1,credit_card,3,150.07,3,office_furniture,8577,itaquaquecetuba,SP
9,20a452f528d487411fd7d3ebda1d0f20,31318a0597cd9d50ce4cfd03c80fe780,37540,santa rita do sapucai,MG,1c7fe02ac4c7be50c59afb295cf85b89,delivered,2018-01-26 13:22:09,2018-01-30 03:47:31,2018-02-09 13:17:44,...,21.76,1,boleto,1,257.50,2,office_furniture,8577,itaquaquecetuba,SP
10,20a452f528d487411fd7d3ebda1d0f20,31318a0597cd9d50ce4cfd03c80fe780,37540,santa rita do sapucai,MG,1c7fe02ac4c7be50c59afb295cf85b89,delivered,2018-01-26 13:22:09,2018-01-30 03:47:31,2018-02-09 13:17:44,...,21.76,1,boleto,1,257.50,2,office_furniture,8577,itaquaquecetuba,SP
11,62f766c82849282806bf2f62ca86432e,83aca63b2193ea126b287f3ae61528d9,89115,gaspar,SC,5ee63c8c9ae2e5c38791b35932cf4c69,delivered,2017-05-09 11:30:18,2017-05-09 11:45:13,2017-05-19 19:32:55,...,15.62,1,credit_card,6,843.66,4,office_furniture,8577,itaquaquecetuba,SP
12,62f766c82849282806bf2f62ca86432e,83aca63b2193ea126b287f3ae61528d9,89115,gaspar,SC,5ee63c8c9ae2e5c38791b35932cf4c69,delivered,2017-05-09 11:30:18,2017-05-09 11:45:13,2017-05-19 19:32:55,...,15.62,1,credit_card,6,843.66,4,office_furniture,8577,itaquaquecetuba,SP
13,62f766c82849282806bf2f62ca86432e,83aca63b2193ea126b287f3ae61528d9,89115,gaspar,SC,5ee63c8c9ae2e5c38791b35932cf4c69,delivered,2017-05-09 11:30:18,2017-05-09 11:45:13,2017-05-19 19:32:55,...,15.62,1,credit_card,6,843.66,4,office_furniture,8577,itaquaquecetuba,SP
14,62f766c82849282806bf2f62ca86432e,83aca63b2193ea126b287f3ae61528d9,89115,gaspar,SC,5ee63c8c9ae2e5c38791b35932cf4c69,delivered,2017-05-09 11:30:18,2017-05-09 11:45:13,2017-05-19 19:32:55,...,15.62,1,credit_card,6,843.66,4,office_furniture,8577,itaquaquecetuba,SP
15,62f766c82849282806bf2f62ca86432e,83aca63b2193ea126b287f3ae61528d9,89115,gaspar,SC,5ee63c8c9ae2e5c38791b35932cf4c69,delivered,2017-05-09 11:30:18,2017-05-09 11:45:13,2017-05-19 19:32:55,...,15.62,1,credit_card,6,843.66,4,office_furniture,8577,itaquaquecetuba,SP
16,62f766c82849282806bf2f62ca86432e,83aca63b2193ea126b287f3ae61528d9,89115,gaspar,SC,5ee63c8c9ae2e5c38791b35932cf4c69,delivered,2017-05-09 11:30:18,2017-05-09 11:45:13,2017-05-19 19:32:55,...,15.62,1,credit_card,6,843.66,4,office_furniture,8577,itaquaquecetuba,SP
17,d3286ca43aa21423c6045b2806ca8e56,acd02fc85cf6339f896c161af2b6abcd,96083,pelotas,RS,b1cc044d321053348a5e482ca7e6b2e3,delivered,2018-01-30 19:29:01,2018-01-30 19:54:04,2018-02-09 13:08:10,...,38.59,1,credit_card,1,145.58,2,office_furniture,8577,itaquaquecetuba,SP
18,c49bec5f74f0413130abdaed8e7621d0,67d6f91d256bdf128fc960a166f413d5,25640,petropolis,RJ,0d831c5aa932379c1cf5b0b1b40b214b,delivered,2017-10-13 10:36:54,2017-10-13 10:49:47,2017-10-24 18:58:49,...,34.18,1,credit_card,1,151.17,3,office_furniture,8577,itaquaquecetuba,SP
19,0058ebe2dc136d918dd001968cfa5903,9e8993ba2665307b71bd1641c2e1cb3d,39495,montalvania,MG,27ae3ad0516a9b55f2236e24f690e01b,delivered,2017-02-09 16:19:02,2017-02-09 16:30:12,2017-02-22 03:51:44,...,15.01,1,credit_card,5,270.00,3,office_furniture,8577,itaquaquecetuba,SP
20,0058ebe2dc136d918dd001968cfa5903,9e8993ba2665307b71bd1641c2e1cb3d,39495,montalvania,MG,27ae3ad0516a9b55f2236e24f690e01b,delivered,2017-02-09 16:19:02,2017-02-09 16:30:12,2017-02-22 03:51:44,...,15.01,1,credit_card,5,270.00,3,office_furniture,8577,itaquaquecetuba,SP
21,f91eb13e253823f25cf9a20fc2d08f56,1c91f8d50340522dd6601237ad13afff,78500,colider,MT,be2463c66944514bb175f7a519a72cd7,delivered,2018-02-07 19:01:48,2018-02-07 19:15:27,2018-02-20 13:59:00,...,43.19,1,credit_card,1,160.18,4,office_furniture,8577,itaquaquecetuba,SP
22,8bf4f9552bc2db14d6195bbbb5131941,b428f59c73c1bbeb3584744b4570654b,3728,sao paulo,SP,7ebc5c60f532934ce55b3025203ebe5b,delivered,2017-06-24 08:59:47,2017-06-27 03:45:30,2017-06-29 17:37:56,...,23.46,1,boleto,1,148.45,2,office_furniture,8577,itaquaquecetuba,SP
23,70bc2fe12d0580eb8336285500defe0e,c71792e0cbb396e0a77258f474d971ab,30672,belo horizonte,MG,66573bb355bdba7b6df55fba794b800d,delivered,2017-10-15 10:30:57,2017-10-15 10:49:15,2017-10-24 22:23:05,...,28.15,1,credit_card,1,141.14,5,office_furniture,8577,itaquaquecetuba,SP
24,11eee0e62a0b905cf878ff13c8aec4a0,7dd466ce70871be5aba0ea1a43df6021,40230,salvador,BA,ff7400d904161b62b6e830b3988f5cbd,delivered,2018-03-27 15:37:03,2018-03-27 15:51:53,2018-04-11 01:05:20,...,37.97,1,credit_card,1,54.96,2,office_furniture,8577,itaquaquecetuba,SP
25,11eee0e62a0b905cf878ff13c8aec4a0,7dd466ce70871be5aba0ea1a43df6021,40230,salvador,BA,ff7400d904161b62b6e830b3988f5cbd,delivered,2018-03-27 15:37:03,2018-03-27 15:51:53,2018-04-11 01:05:20,...,37.97,2,voucher,1,100.00,2,office_furniture,8577,itaquaquecetuba,SP
26,cf4dc8d4be7642c7c05a73188a3d8c1c,35c0fa6f2e6bbb3576e725d22e1066b8,23585,rio de janeiro,RJ,edc9338008f2e9017f842a8bcad3af94,delivered,2017-04-28 16:55:22,2017-04-28 17:10:12,2017-05-12 10:54:53,...,15.04,1,voucher,1,140.03,5,office_furniture,8577,itaquaquecetuba,SP
27,d24a0f00aa18133811d0aa666da75ff6,14803be716853016918954f7ef189abd,29900,linhares,ES,6ee77fd090a49ec9c4e15bd1a94e100e,delivered,2017-03-23 17:44:48,2017-03-25 02:15:36,2017-04-07 15:15:50,...,16.59,1,boleto,1,143.58,5,office_furniture,8577,itaquaquecetuba,SP
28,d1ec48f722227f712bd7c376e194dcc2,5fff3ec8fc85df5fe57190fd9b6543ed,86975,mandaguari,PR,166029aa4dc1bed21f0d50ebdb4ef286,delivered,2018-04-02 09:09:45,2018-04-02 09:28:31,2018-04-16 14:02:55,...,57.08,1,credit_card,10,870.35,5,office_furniture,8577,itaquaquecetuba,SP
29,d1ec48f722227f712bd7c376e194dcc2,5fff3ec8fc85df5fe57190fd9b6543ed,86975,mandaguari,PR,166029aa4dc1bed21f0d50ebdb4ef286,delivered,2018-04-02 09:09:45,2018-04-02 09:28:31,2018-04-16 14:02:55,...,57.08,1,credit_card,10,870.35,5,office_furniture,8577,itaquaquecetuba,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116551,d8b65951c84554c80270720c9b5f1178,c6c805ba1449708b259b6da9375318ec,13201,jundiai,SP,6bcce39be127575854779e39a50f2059,delivered,2018-04-28 02:23:24,2018-05-01 05:32:22,2018-05-04 11:35:00,...,11.15,1,boleto,1,56.15,5,diapers_and_hygiene,6380,carapicuiba,SP
116552,62d3c457010afc957d955568318e6d78,7e3b6916cdc9629811177f17f7ab07ce,3118,sao paulo,SP,796033ffde6ba06e0abe387e36ee8fe0,delivered,2018-08-26 14:17:08,2018-08-26 14:25:15,2018-08-27 07:45:00,...,19.08,1,credit_card,3,158.97,5,diapers_and_hygiene,89063,blumenau,SC
116553,e924482b6903522795771e672721f5d2,ab4a2b8d2a955029eb49579cbb027994,2403,sao paulo,SP,30d7af26cb5f8577b5c6a0164dc814c5,canceled,2018-07-26 12:45:33,2018-07-26 12:55:25,NaT,...,11.22,1,credit_card,3,40.02,1,diapers_and_hygiene,1403,sao paulo,SP
116554,c167ca7e3249df1c0fce76509c0da7bc,c04825f7f2dea64775bba021dd842fdd,44005,feira de santana,BA,d6f7121c5ede8e22d75e57b6e836871f,delivered,2018-08-16 14:42:48,2018-08-16 14:55:21,2018-08-17 08:24:00,...,22.52,1,debit_card,1,107.42,4,cine_photo,9041,santo andre,SP
116555,38278865371cd2796600255e9d1bb872,8092e2240cc0a4ac008c897518f59b01,6023,osasco,SP,618b0e262ba7b2c46a5b349fadbd4996,delivered,2018-05-19 17:48:44,2018-05-22 09:36:46,2018-05-22 13:46:00,...,7.39,1,boleto,1,57.19,5,cine_photo,9041,santo andre,SP
116556,6e888e003d673cdce73296c4b656fefe,4c0ec556021e916e7d469399bf98d09c,13471,americana,SP,549e5c65d1f41cb1c4d307752c3b9eae,delivered,2018-05-22 14:22:51,2018-05-22 14:34:57,2018-05-23 09:07:00,...,7.39,1,credit_card,3,57.19,5,cine_photo,9041,santo andre,SP
116557,51ff0c33aa4696c23727652d9868dfc5,d10687a929e58de647bfda07ce41713e,66823,belem,PA,0ec7299d65db721d9a6b5c95c2ff494a,delivered,2018-05-11 16:51:46,2018-05-11 17:08:39,2018-05-14 09:48:00,...,19.04,1,credit_card,6,68.84,5,cine_photo,9041,santo andre,SP
116558,1f763783a93e0c559a0c7dc847b31eef,158da4c494bfc8f41b20366129483924,23030,rio de janeiro,RJ,bd2f31f2548344a9d1f4ea1c03625e93,delivered,2018-05-17 16:37:22,2018-05-18 00:14:47,2018-05-18 07:13:00,...,15.23,1,credit_card,2,65.03,3,cine_photo,9041,santo andre,SP
116559,4058d823a6156dd8f9a068750310bac5,3381bbc6c746aa5ff869359fb016c9f7,4517,sao paulo,SP,85abe9ebac688730f1c3591c1ca2a167,delivered,2018-05-31 20:13:28,2018-05-31 20:33:08,2018-06-01 10:01:00,...,7.44,1,credit_card,3,90.24,5,cine_photo,9041,santo andre,SP
116560,ca5fc68d665a2ce5392fccbde3475f72,a914b2be4782207abc6758095ec9e8aa,4130,sao paulo,SP,01787af385123b93ba50c5f05530ee12,delivered,2018-05-15 17:33:50,2018-05-15 17:54:29,2018-05-16 09:25:00,...,7.39,1,credit_card,1,114.38,5,cine_photo,9041,santo andre,SP
116561,ca5fc68d665a2ce5392fccbde3475f72,a914b2be4782207abc6758095ec9e8aa,4130,sao paulo,SP,01787af385123b93ba50c5f05530ee12,delivered,2018-05-15 17:33:50,2018-05-15 17:54:29,2018-05-16 09:25:00,...,7.39,1,credit_card,1,114.38,5,cine_photo,9041,santo andre,SP
116562,29e227115fb68d196f0e1dab3c40a622,da8accaa0030a75e2e7848ec481a4828,50070,recife,PE,335cf1cb074c8dfcdf59bc86f8255409,delivered,2018-05-15 09:08:59,2018-05-16 09:33:16,2018-05-16 08:57:00,...,19.04,1,credit_card,6,68.84,5,cine_photo,9041,santo andre,SP
116563,7241aae1af5ffcdb5411a9d23be378ea,0cd7d20504975ef3cd878aaffa80e482,20241,rio de janeiro,RJ,b1e786caeddece12e5efd30580eaaabc,delivered,2018-04-20 08:04:26,2018-04-24 17:46:25,2018-04-23 12:34:51,...,15.23,1,boleto,1,65.03,5,cine_photo,9041,santo andre,SP
116564,2eba59cbdb86a8a535076c9178c8dc3f,2726e5dc94666be0b1fdf08d02eade18,5417,sao paulo,SP,e8dbfb34a57fe34db02546aa50b56f10,delivered,2018-05-16 15:01:23,2018-05-16 15:19:35,2018-05-18 07:13:00,...,7.39,1,credit_card,1,57.19,5,cine_photo,9041,santo andre,SP
116565,704524826c3b6ea14cea19ba0c11ec4e,2852637db607bf7d453e51b172b3e7d6,65075,sao luis,MA,215b38acfb4aef3bb0144656bb102421,delivered,2018-05-18 01:52:29,2018-05-19 03:13:01,2018-05-21 10:39:00,...,22.85,1,boleto,1,72.65,5,cine_photo,9041,santo andre,SP
116566,4e54b60d9094da89bfd9e8006ec8bcba,0195c54646cda6452f5e1a0474f3b502,3377,sao paulo,SP,f203b250a442eac108f23c45f8b1efc8,delivered,2018-05-09 17:18:42,2018-05-11 02:57:42,2018-05-11 10:54:00,...,7.39,1,boleto,1,57.19,5,cine_photo,9041,santo andre,SP
116567,324ec4addc12b40f3f4223fc376185fb,0bf96ae17d786534def0b9f7ae788b14,29167,serra,ES,a71ebda57a67e6349ab52539913f78d8,delivered,2018-07-26 16:24:10,2018-07-26 16:35:10,2018-07-27 10:32:00,...,15.76,1,debit_card,1,110.66,5,cine_photo,9041,santo andre,SP
116568,637321037fb8b34323ce7fd8aab4a0f1,07547425c8f7a7086f529f2d3b80d21a,14806,araraquara,SP,91be51c856a90d7efe86cf9d082d6ae3,delivered,2018-06-12 15:58:03,2018-06-12 16:32:26,2018-06-12 15:44:00,...,19.17,1,credit_card,18,397.90,1,cine_photo,9041,santo andre,SP
116569,d39cfc95a6ba2cbd9cfa6bb862fd8d77,aad1c7f54ec632ddf6ac8b080b27cd27,88333,balneario camboriu,SC,aa4bd1aa4ff7249ea156343f704478a0,delivered,2018-08-18 09:47:18,2018-08-18 09:55:14,2018-08-20 08:49:00,...,18.69,1,debit_card,1,103.59,4,cine_photo,9041,santo andre,SP
116570,ac54eabad353ecdbd32b0d554d99f411,2f521a0cfb4cc68e6ff29a6371d9d850,4350,sao paulo,SP,c9e7721790d06c21ff6fcd2dee7a2f73,delivered,2018-07-04 20:23:40,2018-07-05 16:24:41,2018-07-05 08:39:00,...,8.05,1,credit_card,1,120.95,5,cine_photo,9041,santo andre,SP
116571,c8371460f35fcbaec011347c9e84b020,956431f32e0be7439ae229ff4984bc60,22745,rio de janeiro,RJ,b36511d6ed0cbc11beb1ab142ab3021c,delivered,2018-08-14 14:21:42,2018-08-14 14:35:08,2018-08-15 06:55:00,...,17.09,1,credit_card,1,145.09,5,cine_photo,9041,santo andre,SP
116572,520ac67588ffaaf2c60691f72b4a7dcc,d931428aff71cf37ebd00c5808ea9aba,92320,canoas,RS,a79bd7af35a4fffee2b23fded963b4ea,delivered,2017-04-21 20:16:02,2017-04-21 20:25:22,2017-04-28 14:29:17,...,16.05,1,credit_card,1,41.04,4,fashion_sport,6038,osasco,SP
116573,1a655f9c2a5fd2c3e77940ffdc848989,5408b524d4f3a4ac4e9b7b52d993fae7,95940,arroio do meio,RS,57edfe6486364c7777241f5ab5902715,processing,2017-06-13 10:51:54,2017-06-13 11:03:07,NaT,...,15.10,1,credit_card,4,40.09,1,fashion_sport,6038,osasco,SP
116574,ff09fd7b29e7488a8d8a20badcd8befe,8c21dd8c37144807c601f99f2a209dfb,72587,brasilia,DF,157de1652c032429a625d034be79eeeb,delivered,2017-05-10 09:00:07,2017-05-10 09:10:18,2017-05-15 10:06:54,...,14.10,1,credit_card,3,39.09,5,fashion_sport,6038,osasco,SP
116575,ff09fd7b29e7488a8d8a20badcd8befe,8c21dd8c37144807c601f99f2a209dfb,72587,brasilia,DF,157de1652c032429a625d034be79eeeb,delivered,2017-05-10 09:00:07,2017-05-10 09:10:18,2017-05-15 10:06:54,...,14.10,1,credit_card,3,39.09,5,fashion_sport,6038,osasco,SP
116576,ce2172509c4149d65212484eb761bc37,c5da6424f1f5decedef8672a1a0103e1,88350,brusque,SC,edcf1e1eeb52381be9388c90152be52d,delivered,2018-08-21 11:29:05,2018-08-21 11:50:47,2018-08-21 15:37:00,...,24.83,1,credit_card,5,314.32,5,arts_and_craftmanship,95910,lajeado,RS
116577,ee1cfdc92e449920e25d3ca4ab4da4f6,8d80e477643ec569b24592ce3d9dfc4c,9951,diadema,SP,2ef4a11b6e24fdfbb43b92cb5f95edff,delivered,2018-07-23 18:35:14,2018-07-24 10:31:25,2018-07-24 14:37:00,...,12.86,1,credit_card,1,84.63,3,arts_and_craftmanship,17201,jau,SP
116578,ee1cfdc92e449920e25d3ca4ab4da4f6,8d80e477643ec569b24592ce3d9dfc4c,9951,diadema,SP,2ef4a11b6e24fdfbb43b92cb5f95edff,delivered,2018-07-23 18:35:14,2018-07-24 10:31:25,2018-07-24 14:37:00,...,12.87,1,credit_card,1,84.63,3,arts_and_craftmanship,17201,jau,SP
116579,ab0cf72dfe0538a63a57d6905ccb7b57,8c3c961a52bb5a0ffbce1d4e6d25cd67,35930,joao monlevade,MG,2c12150c742ae2fa48bc703964c16c5f,delivered,2018-07-28 17:55:27,2018-07-29 18:30:31,2018-07-30 14:54:00,...,19.60,1,credit_card,7,77.50,5,arts_and_craftmanship,17201,jau,SP
116580,c61336d6c835632048f973d2f2db598d,428f4721a509be8c52de6ec2900ba918,12305,jacarei,SP,9f7ba492c273ffac8f90a623b8eadd3b,delivered,2018-08-23 12:31:37,2018-08-24 03:24:24,2018-08-24 15:14:00,...,12.79,1,boleto,1,24.69,5,arts_and_craftmanship,17201,jau,SP

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116581 entries, 0 to 116580
Data columns (total 24 columns):
customer_id                      116581 non-null object
customer_unique_id               116581 non-null object
customer_zip_code_prefix         116581 non-null int64
customer_city                    116581 non-null object
customer_state                   116581 non-null object
order_id                         116581 non-null object
order_status                     116581 non-null object
order_purchase_timestamp         116581 non-null datetime64[ns]
order_approved_at                116567 non-null datetime64[ns]
order_delivered_carrier_date     115368 non-null datetime64[ns]
order_delivered_customer_date    114066 non-null datetime64[ns]
order_estimated_delivery_date    116581 non-null datetime64[ns]
seller_id                        116581 non-null object
price                            116581 non-null float64
freight_value                    116581 non-null float64
payment_sequential               116581 non-null int64
payment_type                     116581 non-null object
payment_installments             116581 non-null int64
payment_value                    116581 non-null float64
review_score                     116581 non-null int64
product_category_name_english    116581 non-null object
seller_zip_code_prefix           116581 non-null int64
seller_city                      116581 non-null object
seller_state                     116581 non-null object
dtypes: datetime64[ns](5), float64(3), int64(5), object(11)
memory usage: 22.2+ MB

### Cleaing issues

- No missing data
- product_category_name_english to be changed to product_category

## Data Cleaning

- 'product_category_name_english' to be changed to 'product_category'

In [189]:
df.rename(columns={'product_category_name_english':'product_name'},inplace=True)
#check results
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_name,seller_zip_code_prefix,seller_city,seller_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,21.88,1,credit_card,2,146.87,4,office_furniture,8577,itaquaquecetuba,SP
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,24.90,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,24.90,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,15.62,1,credit_card,7,140.61,3,office_furniture,8577,itaquaquecetuba,SP
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,30.59,1,credit_card,10,137.58,4,office_furniture,8577,itaquaquecetuba,SP

In [190]:
df.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state', 'order_id', 'order_status',
       'order_purchase_timestamp', 'order_approved_at',
       'order_delivered_carrier_date', 'order_delivered_customer_date',
       'order_estimated_delivery_date', 'seller_id', 'price', 'freight_value',
       'payment_sequential', 'payment_type', 'payment_installments',
       'payment_value', 'review_score', 'product_name',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='object')

## Feature Engineering

- approval_timespan
- delivery_timespan
- delivered_on_time

In [191]:
df['approval_timespan']=df['order_approved_at']-df['order_purchase_timestamp']
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,payment_sequential,payment_type,payment_installments,payment_value,review_score,product_name,seller_zip_code_prefix,seller_city,seller_state,approval_timespan
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,1,credit_card,2,146.87,4,office_furniture,8577,itaquaquecetuba,SP,0 days 00:16:37
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP,0 days 23:57:35
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,1,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP,0 days 23:57:35
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,1,credit_card,7,140.61,3,office_furniture,8577,itaquaquecetuba,SP,1 days 02:11:30
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,1,credit_card,10,137.58,4,office_furniture,8577,itaquaquecetuba,SP,1 days 02:43:39

In [192]:
df['delivery_timespan']=df['order_delivered_customer_date']-df['order_approved_at']
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,payment_type,payment_installments,payment_value,review_score,product_name,seller_zip_code_prefix,seller_city,seller_state,approval_timespan,delivery_timespan
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,credit_card,2,146.87,4,office_furniture,8577,itaquaquecetuba,SP,0 days 00:16:37,8 days 19:13:23
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP,0 days 23:57:35,17 days 23:22:02
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,credit_card,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP,0 days 23:57:35,17 days 23:22:02
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,credit_card,7,140.61,3,office_furniture,8577,itaquaquecetuba,SP,1 days 02:11:30,17 days 11:31:08
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,credit_card,10,137.58,4,office_furniture,8577,itaquaquecetuba,SP,1 days 02:43:39,23 days 22:39:41

In [193]:
def order_on_time(estimated_date, delivery_date):
    if estimated_date > delivery_date:
        value = 'Yes'
    else:
        value = 'No'
    return value

In [194]:
df['order_on_time'] = df.apply(lambda x: order_on_time(x['order_estimated_delivery_date'], x['order_delivered_customer_date']), axis=1)
df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,payment_installments,payment_value,review_score,product_name,seller_zip_code_prefix,seller_city,seller_state,approval_timespan,delivery_timespan,order_on_time
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,2,146.87,4,office_furniture,8577,itaquaquecetuba,SP,0 days 00:16:37,8 days 19:13:23,Yes
1,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP,0 days 23:57:35,17 days 23:22:02,Yes
2,8912fc0c3bbf1e2fbf35819e21706718,9eae34bbd3a474ec5d07949ca7de67c0,68030,santarem,PA,c1d2b34febe9cd269e378117d6681172,delivered,2017-11-09 00:50:13,2017-11-10 00:47:48,2017-11-22 01:43:37,...,1,275.79,1,office_furniture,8577,itaquaquecetuba,SP,0 days 23:57:35,17 days 23:22:02,Yes
3,f0ac8e5a239118859b1734e1087cbb1f,3c799d181c34d51f6d44bbbc563024db,92480,nova santa rita,RS,b1a5d5365d330d10485e0203d54ab9e8,delivered,2017-05-07 20:11:26,2017-05-08 22:22:56,2017-05-19 20:16:31,...,7,140.61,3,office_furniture,8577,itaquaquecetuba,SP,1 days 02:11:30,17 days 11:31:08,Yes
4,6bc8d08963a135220ed6c6d098831f84,23397e992b09769faf5e66f9e171a241,25931,mage,RJ,2e604b3614664aa66867856dba7e61b7,delivered,2018-02-03 19:45:40,2018-02-04 22:29:19,2018-02-19 18:21:47,...,10,137.58,4,office_furniture,8577,itaquaquecetuba,SP,1 days 02:43:39,23 days 22:39:41,Yes

## Save DataFrame as 'orders_dataset'

In [195]:
df.to_csv('orders_dataset.csv')